/* Generated By:JavaCC: Do not edit this line. AstParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AstParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SLComment = 6;
  /** RegularExpression Id. */
  int kwArrayElm = 7;
  /** RegularExpression Id. */
  int kwArrayType = 8;
  /** RegularExpression Id. */
  int kwAssign = 9;
  /** RegularExpression Id. */
  int kwBinop = 10;
  /** RegularExpression Id. */
  int kwBoolType = 11;
  /** RegularExpression Id. */
  int kwCall = 12;
  /** RegularExpression Id. */
  int kwCallStmt = 13;
  /** RegularExpression Id. */
  int kwClassDecl = 14;
  /** RegularExpression Id. */
  int kwElse = 15;
  /** RegularExpression Id. */
  int kwFalse = 16;
  /** RegularExpression Id. */
  int kwField = 17;
  /** RegularExpression Id. */
  int kwIf = 18;
  /** RegularExpression Id. */
  int kwIntType = 19;
  /** RegularExpression Id. */
  int kwIntVal = 20;
  /** RegularExpression Id. */
  int kwMethodDecl = 21;
  /** RegularExpression Id. */
  int kwNewArray = 22;
  /** RegularExpression Id. */
  int kwNewObj = 23;
  /** RegularExpression Id. */
  int kwObjType = 24;
  /** RegularExpression Id. */
  int kwParam = 25;
  /** RegularExpression Id. */
  int kwPrint = 26;
  /** RegularExpression Id. */
  int kwReturn = 27;
  /** RegularExpression Id. */
  int kwStrVal = 28;
  /** RegularExpression Id. */
  int kwThis = 29;
  /** RegularExpression Id. */
  int kwUnop = 30;
  /** RegularExpression Id. */
  int kwVarDecl = 31;
  /** RegularExpression Id. */
  int kwVoid = 32;
  /** RegularExpression Id. */
  int kwWhile = 33;
  /** RegularExpression Id. */
  int BoolLit = 34;
  /** RegularExpression Id. */
  int Digit = 35;
  /** RegularExpression Id. */
  int Letter = 36;
  /** RegularExpression Id. */
  int IntLit = 37;
  /** RegularExpression Id. */
  int StrLit = 38;
  /** RegularExpression Id. */
  int Id = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SLComment>",
    "\"ArrayElm\"",
    "\"ArrayType\"",
    "\"Assign\"",
    "\"Binop\"",
    "\"BoolType\"",
    "\"Call\"",
    "\"CallStmt\"",
    "\"ClassDecl\"",
    "\"Else\"",
    "\"False\"",
    "\"Field\"",
    "\"If\"",
    "\"IntType\"",
    "\"IntVal\"",
    "\"MethodDecl\"",
    "\"NewArray\"",
    "\"NewObj\"",
    "\"ObjType\"",
    "\"Param\"",
    "\"Print\"",
    "\"Return\"",
    "\"StrVal\"",
    "\"This\"",
    "\"Unop\"",
    "\"VarDecl\"",
    "\"void\"",
    "\"While\"",
    "<BoolLit>",
    "<Digit>",
    "<Letter>",
    "<IntLit>",
    "<StrLit>",
    "<Id>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"!\"",
  };

}
